# Generated by Django 4.2.1 on 2024-05-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
    ]
